{% set data = load_setup_py_data() %}

package:
  name: psdm_qs_cli
  version: {{ data.get('version') }}

source:
  path : ..

build:
  number: 1
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - krtc
    - requests
    - six
  run:
    - python
    - setuptools
    - krtc
    - requests
    - six

about:
  home: https://github.com/slaclab/psdm_qs_cli.git
  license: MIT License
