{% set data = load_setup_py_data() %}

package:
  name: psdm_qs_cli
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/slaclab/psdm_qs_cli.git
  git_tag: "0.0.5"

build:
  script:
    - pip install --no-deps --disable-pip-version-check .

requirements:
  build:
    - python
    - setuptools
    - krtc
    - requests
  run:
    - python
    - setuptools
    - krtc
    - requests

about:
  home: https://github.com/slaclab/psdm_qs_cli.git
  license: MIT License
